import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Iframe from 'react-iframe'
import { ImTwitch } from 'react-icons/im';

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      <div className="row" >
          <div className="row justify-content-center mt-5">
            <div className="col-md-3">
              <div className="card">
                <div className="card-body">
                  
                  <div className="text-center mb-2">
                    <ImTwitch size={40} fill="#9102C3"/>
                  </div>

                  <form method="post">
                    <div className="form-group">
                      <input type="email" className="form-control" id="" aria-describedby="" placeholder="Stream name" style={{borderColor : '#7367F0'}}/>
                    </div>
                    <div className="text-center mt-3">
                      <button className='btn btn-md text-white' style={{ backgroundColor : '#7367F0'}}>Watch</button>
                    </div>
                  </form>

                </div>
              </div>
            </div>
          </div>
      </div>

      {/* <Iframe url="https://player.twitch.tv/?channel=baiano&muted=true&parent=localhost"
        width="640px"
        height="320px"
        id=""
        className=""
        display="block"
        position="relative"/> */}
      
    </>
  )
}
